/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.text.SimpleDateFormat;
import java.util.Date;

public class frmPrincipal extends javax.swing.JFrame {

    public frmPrincipal() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
       
        this.setTitle("Sistema Peluqueria");
        
//        Date date = new Date();
//        String format = new String("dd/MM/yyyy");
//        SimpleDateFormat formato = new SimpleDateFormat(format);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnsalir = new javax.swing.JMenuItem();
        mnLocalizaciones = new javax.swing.JMenu();
        mnRegion = new javax.swing.JMenuItem();
        mndepto = new javax.swing.JMenuItem();
        mnDistrito = new javax.swing.JMenuItem();
        mnAjustes = new javax.swing.JMenu();
        mnajustarusuario = new javax.swing.JMenuItem();
        mncliente = new javax.swing.JMenuItem();
        mnproveedor = new javax.swing.JMenuItem();
        mnAjustarProducto = new javax.swing.JMenuItem();
        mnfactura2 = new javax.swing.JMenu();
        mnPEDIDO1 = new javax.swing.JMenuItem();
        mnAGENDAMIENTO = new javax.swing.JMenu();
        mnAGENDA = new javax.swing.JMenuItem();
        mnfactura = new javax.swing.JMenu();
        mnFacturaCompra = new javax.swing.JMenuItem();
        mnFacturaVenta = new javax.swing.JMenuItem();
        informe = new javax.swing.JMenu();
        mnPEDIDO2 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1476, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnsalir.setText("Salir");
        mnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnsalir);

        jMenuBar1.add(jMenu1);

        mnLocalizaciones.setText("Localizaciones");

        mnRegion.setText("Ajustar Region");
        mnRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegionActionPerformed(evt);
            }
        });
        mnLocalizaciones.add(mnRegion);

        mndepto.setText("Ajustar Departamento");
        mndepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndeptoActionPerformed(evt);
            }
        });
        mnLocalizaciones.add(mndepto);

        mnDistrito.setText("Ajustar Distrito");
        mnDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDistritoActionPerformed(evt);
            }
        });
        mnLocalizaciones.add(mnDistrito);

        jMenuBar1.add(mnLocalizaciones);

        mnAjustes.setText("Ajustes");

        mnajustarusuario.setText("Ajustar Usuario");
        mnajustarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnajustarusuarioActionPerformed(evt);
            }
        });
        mnAjustes.add(mnajustarusuario);

        mncliente.setText("ajustar Cliente");
        mncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnclienteActionPerformed(evt);
            }
        });
        mnAjustes.add(mncliente);

        mnproveedor.setText("Ajustar Proveedor");
        mnproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnproveedorActionPerformed(evt);
            }
        });
        mnAjustes.add(mnproveedor);

        mnAjustarProducto.setText("Ajustar Producto");
        mnAjustarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAjustarProductoActionPerformed(evt);
            }
        });
        mnAjustes.add(mnAjustarProducto);

        jMenuBar1.add(mnAjustes);

        mnfactura2.setText("pedido_compra");

        mnPEDIDO1.setText("pedido");
        mnPEDIDO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPEDIDO1ActionPerformed(evt);
            }
        });
        mnfactura2.add(mnPEDIDO1);

        jMenuBar1.add(mnfactura2);

        mnAGENDAMIENTO.setText("Agendamiento");

        mnAGENDA.setText("agendar citas");
        mnAGENDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAGENDAActionPerformed(evt);
            }
        });
        mnAGENDAMIENTO.add(mnAGENDA);

        jMenuBar1.add(mnAGENDAMIENTO);

        mnfactura.setText("facturas");

        mnFacturaCompra.setText("facturaCompra");
        mnFacturaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFacturaCompraActionPerformed(evt);
            }
        });
        mnfactura.add(mnFacturaCompra);

        mnFacturaVenta.setText("factura Venta");
        mnFacturaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFacturaVentaActionPerformed(evt);
            }
        });
        mnfactura.add(mnFacturaVenta);

        jMenuBar1.add(mnfactura);

        informe.setText("Informes");
        informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeActionPerformed(evt);
            }
        });

        mnPEDIDO2.setText("Informe General");
        mnPEDIDO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPEDIDO2ActionPerformed(evt);
            }
        });
        informe.add(mnPEDIDO2);

        jMenuBar1.add(informe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDistritoActionPerformed
        FRM_distrito form = new FRM_distrito();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnDistritoActionPerformed

    private void mndeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndeptoActionPerformed
        FRM_departamento form = new FRM_departamento();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mndeptoActionPerformed

    private void mnRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegionActionPerformed
        FRM_region form = new FRM_region();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnRegionActionPerformed

    private void mnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_mnsalirActionPerformed

    private void mnajustarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnajustarusuarioActionPerformed
        FRM_empleados form = new FRM_empleados();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnajustarusuarioActionPerformed

    private void mnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnclienteActionPerformed
        FRM_clientes form = new FRM_clientes();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnclienteActionPerformed

    private void mnproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnproveedorActionPerformed
        FRM_proveedor form = new FRM_proveedor();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnproveedorActionPerformed

    private void mnAjustarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAjustarProductoActionPerformed
        FRM_INSUMO form = new FRM_INSUMO();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnAjustarProductoActionPerformed

    private void mnFacturaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFacturaCompraActionPerformed
        FRM_pv form = new FRM_pv();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnFacturaCompraActionPerformed

    private void mnFacturaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFacturaVentaActionPerformed
        frm_facturaVenta form = new frm_facturaVenta();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnFacturaVentaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnAGENDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAGENDAActionPerformed
        // TODO add your handling code here:
        frm_agendamiento form = new frm_agendamiento();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnAGENDAActionPerformed

    private void mnPEDIDO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPEDIDO1ActionPerformed
        // TODO add your handling code here:
        FRM_pedidos_compras form = new FRM_pedidos_compras();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnPEDIDO1ActionPerformed

    private void mnPEDIDO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPEDIDO2ActionPerformed
        // TODO add your handling code here:
         FORMULARIOSinformes form = new FORMULARIOSinformes();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_mnPEDIDO2ActionPerformed

    private void informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeActionPerformed
        // TODO add your handling code here:
        FORMULARIOSinformes form = new FORMULARIOSinformes();
        escritorio.add(form);
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_informeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    public static javax.swing.JMenu informe;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenuItem mnAGENDA;
    public static javax.swing.JMenu mnAGENDAMIENTO;
    public static javax.swing.JMenuItem mnAjustarProducto;
    public static javax.swing.JMenu mnAjustes;
    private javax.swing.JMenuItem mnDistrito;
    public static javax.swing.JMenuItem mnFacturaCompra;
    private javax.swing.JMenuItem mnFacturaVenta;
    public static javax.swing.JMenu mnLocalizaciones;
    public static javax.swing.JMenuItem mnPEDIDO1;
    public static javax.swing.JMenuItem mnPEDIDO2;
    private javax.swing.JMenuItem mnRegion;
    public static javax.swing.JMenuItem mnajustarusuario;
    private javax.swing.JMenuItem mncliente;
    private javax.swing.JMenuItem mndepto;
    public static javax.swing.JMenu mnfactura;
    public static javax.swing.JMenu mnfactura2;
    private javax.swing.JMenuItem mnproveedor;
    private javax.swing.JMenuItem mnsalir;
    // End of variables declaration//GEN-END:variables
}
